---
- name: "Set timezone to Asia/Tokyo"
  become: yes
  become_user: root
  timezone:
    name: Asia/Tokyo

- name: "Set NTP Server"
  become: yes
  become_user: root
  shell:
    perl -pi -e 's|^#(NTP)=.*$|$1=169.254.169.123|g' /etc/systemd/timesyncd.conf

- name: "Restart systemd-timesyncd.service"
  become: yes
  become_user: root
  systemd:
    state: restarted
    name: "systemd-timesyncd.service"
    enabled: "yes"