---
- name: Make Directory ~/isubnb/webapp/backend/java/src/main/resources/sql
  become: yes
  become_user: isucon
  file: 
    path: /home/isucon/isubnb/webapp/backend/java/src/main/resources/sql
    state: directory

- name: Deploy sql
  become: yes
  become_user: isucon
  shell: |
    cp -pR /home/isucon/isubnb/webapp/backend/mysql/db/* /home/isucon/isubnb/webapp/backend/java/src/main/resources/sql

- name: Package Java App
  become: yes
  become_user: isucon
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/python/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  args:
    chdir: /home/isucon/isubnb/webapp/backend/java
  shell: |
    ./mvnw clean package

- name: Copy Service file
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - isubnb.java.service
