---
- name: Install isubnb.python Pacakges
  become: yes
  become_user: isucon
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/python/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  args:
    chdir: /home/isucon/isubnb/webapp/backend/python
  shell: |
    poetry config virtualenvs.create false && poetry install

- name: Copy Service file
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - isubnb.python.service
