---
- name: Build Web Application Go
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/isubnb/webapp/backend/go/
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/local/python/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  shell: |
    go build -o isubnb

- name: Copy Service file
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - isubnb.go.service
